# Generated by Django 5.1.4 on 2025-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
